Repository dali-lab/pine-beetle-frontend, pull requests merged in 2021-01, with the labels that each got.

#495 Add about page with project credits
  src/app.js
  src/components/header/component.js
  src/constants/index.js
  src/screens/about/component.js
  src/screens/about/index.js
  src/screens/about/style.scss
  src/screens/index.js
Labels: dev, frontend

#496 DEV TO RELEASE | About page + README updates
  README.md
  src/app.js
  src/components/header/component.js
  src/constants/index.js
  src/screens/about/component.js
  src/screens/about/index.js
  src/screens/about/style.scss
  src/screens/index.js
Labels: RELEASE

#503 upload guide and navbar fix
  src/components/header/component.js
  src/components/header/style.scss
  src/screens/admin/component.js
  src/screens/admin/components/file-upload/component.js
  src/screens/admin/style.scss
Labels: dev, documentation, frontend

#504 Add video to home screen
  src/constants/index.js
  src/screens/home/component.js
  src/screens/home/style.scss
Labels: dev, frontend

#505 DEV TO RELEASE | Admin guide and home page video
  src/components/header/component.js
  src/components/header/style.scss
  src/constants/index.js
  src/screens/admin/component.js
  src/screens/admin/components/file-upload/component.js
  src/screens/admin/style.scss
  src/screens/home/component.js
  src/screens/home/style.scss
Labels: RELEASE
