Repository dali-lab/pine-beetle-frontend, pull requests merged in 2022-01, with the labels that each got.

#519 Bump package versions for dependabot
  package.json
  yarn.lock
Labels: frontend, dev, dependencies

#521 Title change
  package.json
  src/components/header/component.js
  src/components/header/style.scss
  src/constants/index.js
  src/screens/home/component.js
  src/screens/trapping-data/components/overview-text/component.js
  yarn.lock
Labels: frontend, dev

#534 Use environment variables for server environments
  .env.example
  src/constants/index.js
  src/index.js
Labels: frontend, dev, bug
